Prevent to draw null-character at the end of each string.
digitalgust/miniJVM pull request #13
Opened 2022-05-01 19:06 UTC by Starcommander

Using a different font all GLabel and GButton and other objects draws an unknown character [X] at the end of each font-string.
The used default-font seems to draw a null-string with nothing instead.
As it is not necessary to draw the null-character we can and should skip it.

2022-05-01 19:30 UTC, Starcommander commented
Example fonts that draws unknown character:
https://github.com/adobe-fonts/source-sans
https://github.com/adobe-fonts/source-code-pro

2022-05-01 23:34 UTC, digitalgust requested changes
Because jni_nanovg.c is generated by Nanovg_java_2_c.java, So it cant be modifies manual, I changed the "deps/include/nanovg/nanovg_jni_assist.h"

```
float nvgTextJni(NVGcontext *ctx, float x, float y, const char *string, int start, int end) {
    return nvgText(ctx, x, y, string + start, string + end - 1);
}
```

2022-05-02 16:44 UTC, Starcommander commented
Yes, this commit seems to solve this issue on an other code position.
(I don't exactly understand, why you generate some files.)
Thanks for fixing this.
I think I can close the PR now, right?

2022-05-02 22:05 UTC, Starcommander commented
Unfortunately the commit breaks the main app with original font.
Seems not in each case the last character is a null-character.
(In this case the multiline textfield shows "Massag " instead of "Massage")

So I can fix this with requesting the last character: `if (end > 0 && string[end-1] == 0) { end--; }`
![grafik](https://user-images.githubusercontent.com/3107385/166334411-d24bc438-a81d-4ccd-a2b8-5a6aa452fc09.png)

Should I create a new pull-request again?

2022-05-03 02:22 UTC, digitalgust commented
submitted again.

2022-05-03 17:34 UTC, Starcommander commented
Thanks again for the fast response and fix.

2022-05-03 17:34 UTC, closed without merging